# Generated by Django 3.2.7 on 2022-01-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0003_remove_quotation_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_order', to='BusinessSecurity.order'),
        ),
    ]
