# Generated by Django 3.2.7 on 2022-01-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0004_alter_quotation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
