# Generated by Django 3.2.7 on 2022-01-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0006_auto_20220101_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='agree',
            new_name='agree_to_nda_ncs',
        ),
        migrations.AddField(
            model_name='quotation',
            name='agree_to_quotation',
            field=models.BooleanField(default=False),
        ),
    ]
