# Generated by Django 3.2.7 on 2022-01-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0007_auto_20220101_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='quotation',
        ),
    ]
