# Generated by Django 3.2.7 on 2022-01-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0008_remove_quotation_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='agree_to_nda_ncs',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], default='disagree', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='agree_to_quotation',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], default='disagree', max_length=255),
        ),
    ]
