# Generated by Django 3.2.7 on 2022-01-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0009_auto_20220101_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='agree_to_nda_ncs',
            new_name='agree_to_nda_nca',
        ),
    ]
