# Generated by Django 3.2.7 on 2022-01-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0010_rename_agree_to_nda_ncs_quotation_agree_to_nda_nca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('attending', 'Attending'), ('agreed_to_quotation', 'Agreed To Quotation'), ('agreed_to_nda_nca', 'Agreed To NDA/NCA'), ('disagreed', 'Disagreed'), ('on_progress', 'On Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='new', max_length=250),
        ),
    ]
