# Generated by Django 3.2.7 on 2022-01-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0012_alter_notification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category_choice',
            field=models.CharField(max_length=255),
        ),
    ]
