# Generated by Django 3.2.7 on 2022-01-07 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0018_remove_events_time_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date_field',
        ),
        migrations.AddField(
            model_name='events',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
