# Generated by Django 3.2.7 on 2022-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0019_auto_20220107_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_category',
            field=models.CharField(choices=[('technical_issue', 'Technical Issue'), ('Billing Issue', 'Billing Issue'), ('service_issue', 'Service Issue')], default='technical_issue', max_length=255),
            preserve_default=False,
        ),
    ]
