# Generated by Django 3.2.7 on 2022-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0020_ticket_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_category',
            field=models.CharField(choices=[('technical_issue', 'Technical Issue'), ('billing_issue', 'Billing Issue'), ('service_issue', 'Service Issue')], max_length=255),
        ),
    ]
