# Generated by Django 3.2.7 on 2022-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0024_alter_ticket_ticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='company_name',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
