# Generated by Django 3.2.7 on 2022-01-18 09:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0027_rename_is_new_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='agree_to_nda_nca',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='agree_to_quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='agreement',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], default='disagree', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('attending', 'Attending'), ('uploaded', 'Uploaded'), ('agreed_to_nda_nca', 'Agreed To NDA/NCA'), ('disagreed', 'Disagreed'), ('on_progress', 'On Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='new', max_length=250),
        ),
        migrations.CreateModel(
            name='QuotationAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nda', models.FileField(blank=True, null=True, upload_to='nda/')),
                ('nca', models.FileField(blank=True, null=True, upload_to='nca/')),
                ('message', tinymce.models.HTMLField(blank=True, null=True)),
                ('agreement', models.BooleanField(verbose_name='Agree to NDA/NCA')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_agreement_quotation', to='BusinessSecurity.quotation')),
            ],
        ),
    ]
