# Generated by Django 3.2.7 on 2022-01-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0028_auto_20220118_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationagreement',
            name='nca',
            field=models.FileField(blank=True, null=True, upload_to='nca/uploaded/'),
        ),
        migrations.AlterField(
            model_name='quotationagreement',
            name='nda',
            field=models.FileField(blank=True, null=True, upload_to='nda/uploaded/'),
        ),
    ]
