# Generated by Django 3.2.7 on 2022-01-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0029_auto_20220118_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationagreement',
            name='nca',
        ),
        migrations.RemoveField(
            model_name='quotationagreement',
            name='nda',
        ),
        migrations.AddField(
            model_name='quotationagreement',
            name='user_nca',
            field=models.FileField(blank=True, null=True, upload_to='nca/uploaded/', verbose_name='Upload NCA'),
        ),
        migrations.AddField(
            model_name='quotationagreement',
            name='user_nda',
            field=models.FileField(blank=True, null=True, upload_to='nda/uploaded/', verbose_name='Upload NDA'),
        ),
    ]
