# Generated by Django 3.2.7 on 2022-01-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0030_auto_20220118_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationagreement',
            name='agreement',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agree to NDA/NCA'),
        ),
    ]
