# Generated by Django 3.2.7 on 2022-01-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0031_alter_quotationagreement_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationagreement',
            name='agreement',
        ),
    ]
