# Generated by Django 3.2.7 on 2022-01-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0032_remove_quotationagreement_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationagreement',
            name='agreement',
            field=models.BooleanField(blank=True, default=True, verbose_name='Agree to NDA/NCA'),
        ),
    ]
