# Generated by Django 3.2.7 on 2022-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0033_quotationagreement_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationagreement',
            name='agreement',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], max_length=255, verbose_name='Agree to NDA/NCA'),
        ),
    ]
