# Generated by Django 3.2.7 on 2022-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0035_auto_20220120_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='category_choice',
            field=models.CharField(choices=[('bcs', 'BCS'), ('pcs', 'PCS')], default='bcs', max_length=255),
            preserve_default=False,
        ),
    ]
