# Generated by Django 3.2.7 on 2022-01-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0039_alter_orderprice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprice',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('bank_check', 'Bank Check'), ('card', 'Card'), ('cash', 'Cash'), ('wire_transfer', 'Wire Transfer')], max_length=255),
        ),
    ]
