# Generated by Django 3.2.7 on 2022-02-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0041_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
