# Generated by Django 3.2.7 on 2022-02-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0042_alter_adminnotification_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionbasedpackage',
            name='max_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
