# Generated by Django 3.2.7 on 2022-02-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0043_subscriptionbasedpackage_max_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionbasedpackage',
            name='max_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
