# Generated by Django 3.2.7 on 2022-02-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0044_alter_subscriptionbasedpackage_max_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionbasedpackage',
            name='category_choice',
            field=models.CharField(choices=[('bcs', 'BCS'), ('pcs', 'PCS')], default='bcs', max_length=255),
            preserve_default=False,
        ),
    ]
