# Generated by Django 3.2.7 on 2022-02-03 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessSecurity', '0045_subscriptionbasedpackage_category_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptioninput_inputfield', to='BusinessSecurity.inputfields')),
                ('subscription_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptioninput_subscriptionfield', to='BusinessSecurity.subscriptionfield')),
            ],
            options={
                'db_table': 'BusinessSecurity_subscriptionfield_inputfields',
            },
        ),
        migrations.CreateModel(
            name='TeamSubscriptionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputinfo', models.CharField(max_length=255)),
                ('inputfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputfield_subscriptioninput', to='BusinessSecurity.subscriptioninput')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_subscription_input', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionfield',
            name='fields',
            field=models.ManyToManyField(related_name='subscriptionservice_inputfields', through='BusinessSecurity.SubscriptionInput', to='BusinessSecurity.InputFields'),
        ),
        migrations.AddField(
            model_name='subscriptionfield',
            name='subscriptionservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionservice_service', to='BusinessSecurity.subscriptionservices'),
        ),
    ]
