# Generated by Django 3.2.7 on 2022-02-03 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0046_auto_20220203_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfield',
            name='subscriptionservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionservice_service', to='BusinessSecurity.subscriptionservices', unique=True),
        ),
    ]
