# Generated by Django 3.2.7 on 2022-02-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0049_alter_subscriptionteam_subscription_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionteam',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionteam_business', to='BusinessSecurity.business'),
            preserve_default=False,
        ),
    ]
