# Generated by Django 3.2.7 on 2022-02-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0051_alter_subscriptionfield_subscriptionservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprice',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderprice',
            name='initial_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderprice',
            name='processing_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderprice',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderprice',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
