# Generated by Django 3.2.7 on 2022-02-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0052_auto_20220207_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprice',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='orderprice',
            name='tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Tax (%)'),
        ),
    ]
