# Generated by Django 3.2.7 on 2022-02-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0053_auto_20220207_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprice',
            name='invoice',
            field=models.FileField(default='invoice/invoice.pdf', upload_to='invoice'),
        ),
    ]
