# Generated by Django 3.2.7 on 2022-02-08 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0054_orderprice_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprice',
            name='invoice',
            field=models.FileField(default='invoice/invoice.pdf', upload_to='invoice', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='nca',
            field=models.FileField(blank=True, null=True, upload_to='nca/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='nda',
            field=models.FileField(blank=True, null=True, upload_to='nda/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='quotationagreement',
            name='user_nca',
            field=models.FileField(blank=True, null=True, upload_to='nca/uploaded/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Upload NCA'),
        ),
        migrations.AlterField(
            model_name='quotationagreement',
            name='user_nda',
            field=models.FileField(blank=True, null=True, upload_to='nda/uploaded/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Upload NDA'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_attachment',
            field=models.FileField(upload_to='ticket/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'ogv', 'mkv', 'webm', 'apng', 'avif', 'gif', 'jpeg', 'jpg', 'png', 'svg', 'webp', 'bmp', 'mp3', 'wav', 'ogg', 'pdf', 'csv'])], verbose_name='Attachment'),
        ),
    ]
