# Generated by Django 3.2.7 on 2022-02-09 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0055_auto_20220208_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprice',
            name='invoice',
            field=models.FileField(upload_to='invoice', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
