# Generated by Django 3.2.7 on 2022-02-09 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0056_alter_orderprice_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='nca',
            field=models.FileField(blank=True, help_text='Upload only pdf file', null=True, upload_to='nca/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='nda',
            field=models.FileField(blank=True, help_text='Upload only pdf file', null=True, upload_to='nda/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
