# Generated by Django 3.2.7 on 2022-02-09 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0058_auto_20220209_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprice',
            name='invoice',
            field=models.FileField(help_text='(Supported Format: .pdf)', upload_to='invoice', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='quotationagreement',
            name='user_nca',
            field=models.FileField(blank=True, help_text='(Supported Format: .pdf)', null=True, upload_to='nca/uploaded/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Upload NCA'),
        ),
        migrations.AlterField(
            model_name='quotationagreement',
            name='user_nda',
            field=models.FileField(blank=True, help_text='(Supported Format: .pdf)', null=True, upload_to='nda/uploaded/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Upload NDA'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_attachment',
            field=models.FileField(help_text='(Supported Format: Video/Audio/Images/Documents)', upload_to='ticket/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'ogv', 'mkv', 'webm', 'apng', 'avif', 'gif', 'jpeg', 'jpg', 'png', 'svg', 'webp', 'bmp', 'mp3', 'wav', 'ogg', 'pdf', 'csv'])], verbose_name='Attachment'),
        ),
    ]
