# Generated by Django 3.2.7 on 2022-03-21 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0059_auto_20220209_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_attachment',
            field=models.FileField(blank=True, help_text='(Supported Format: Video/Audio/Images/Documents)', upload_to='ticket/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'ogv', 'mkv', 'webm', 'apng', 'avif', 'gif', 'jpeg', 'jpg', 'png', 'svg', 'webp', 'bmp', 'mp3', 'wav', 'ogg', 'pdf', 'csv'])], verbose_name='Attachment'),
        ),
    ]
