# Generated by Django 3.2.7 on 2022-04-25 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0061_alter_ticket_ticket_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='nda',
            new_name='nda_and_nca',
        ),
        migrations.RemoveField(
            model_name='orderprice',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='nca',
        ),
        migrations.RemoveField(
            model_name='quotationagreement',
            name='user_nca',
        ),
        migrations.RemoveField(
            model_name='quotationagreement',
            name='user_nda',
        ),
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.ImageField(default='events/default.jpg', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice',
            field=models.FileField(blank=True, help_text='(Supported Format: .pdf)', null=True, upload_to='invoice/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='quotationagreement',
            name='user_nda_nca',
            field=models.FileField(blank=True, help_text='(Supported Format: .pdf)', null=True, upload_to='nda/uploaded/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Upload NDA and NCA'),
        ),
    ]
