# Generated by Django 3.2.7 on 2021-12-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0002_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
