# Generated by Django 3.2.7 on 2021-12-29 06:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0006_course_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCSCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=264)),
                ('short_description', models.TextField(max_length=1000)),
                ('long_description', tinymce.models.HTMLField(max_length=5000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcscourse_coursecategory', to='Academy.coursecategory')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='product_id',
        ),
        migrations.CreateModel(
            name='BCSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=264)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcssection_bcscourse', to='Academy.bcscourse')),
            ],
        ),
        migrations.CreateModel(
            name='BCSContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=264)),
                ('text_instruction', models.FileField(upload_to='course/')),
                ('course_video', models.FileField(upload_to='course/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='course/')),
                ('resource_file', models.FileField(upload_to='course/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcscontent_bcssection', to='Academy.bcssection')),
            ],
        ),
    ]
