# Generated by Django 3.2.7 on 2021-12-29 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Academy', '0007_auto_20211229_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(blank=True, max_length=255)),
                ('package_name', models.CharField(max_length=264, verbose_name='Package Name')),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=264)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Subscription Based Courses',
            },
        ),
        migrations.AlterModelOptions(
            name='bcscourse',
            options={},
        ),
        migrations.CreateModel(
            name='PackageFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=264, verbose_name='Feature Name')),
                ('feature', models.CharField(max_length=264, verbose_name='Feature')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagefeature_coursepackage', to='Academy.coursepackage')),
            ],
            options={
                'verbose_name_plural': 'Package Features',
            },
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursepackage_bcscourse', to='Academy.bcscourse'),
        ),
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(max_length=254)),
                ('paypal_id', models.CharField(max_length=255)),
                ('paypal_user_name', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseorder_bcscourse', to='Academy.bcscourse')),
                ('course_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseorder_coursepackage', to='Academy.coursepackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseorder_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
