# Generated by Django 3.2.7 on 2021-12-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0008_auto_20211229_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepackage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagefeatures',
            options={},
        ),
        migrations.RemoveField(
            model_name='coursepackage',
            name='price',
        ),
    ]
