# Generated by Django 3.2.7 on 2021-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0009_auto_20211229_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
