# Generated by Django 3.2.7 on 2022-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0010_coursepackage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='max_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
