# Generated by Django 3.2.7 on 2022-02-08 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0012_auto_20220207_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text_instruction',
            field=models.FileField(upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['txt', 'TXT'])]),
        ),
    ]
