# Generated by Django 3.2.7 on 2022-02-08 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessSecurity', '0055_auto_20220208_0946'),
        ('Academy', '0014_auto_20220208_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subscriptionteam_business', to='BusinessSecurity.business')),
                ('subscription_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionteam_courseorder', to='Academy.courseorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subscriptionteam_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
