# Generated by Django 3.2.7 on 2022-02-09 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0015_subscriptionteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcscontent',
            name='course_video',
            field=models.FileField(help_text='(Video File Only)', upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'ogv', 'mkv', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='bcscontent',
            name='preview_video',
            field=models.FileField(blank=True, help_text='(Video File Only)', null=True, upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'ogv', 'mkv', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='bcscontent',
            name='resource_file',
            field=models.FileField(help_text='(Supported Format: .pdf)', upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='bcscontent',
            name='text_instruction',
            field=models.FileField(help_text='(Supported Format: .txt)', upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
        migrations.AlterField(
            model_name='content',
            name='course_video',
            field=models.FileField(help_text='(Video File Only)', upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'ogv', 'mkv', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='content',
            name='preview_video',
            field=models.FileField(blank=True, help_text='(Video File Only)', null=True, upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'ogv', 'mkv', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='content',
            name='resource_file',
            field=models.FileField(help_text='(Supported Format: .pdf)', upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_instruction',
            field=models.FileField(help_text='(Supported Format: .txt)', upload_to='course/', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
